name: Publish Package with SHA Metadata

on:
  push:
    branches: [main]

env:
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/

      - name: Inject +SHA version temporarily
        run: |
          ORIG_VERSION=$(node -p "require('./package.json').version")
          echo "ORIG_VERSION=$ORIG_VERSION" >> $GITHUB_ENV

          SHA=$(git rev-parse --short HEAD)
          TMP_VERSION="${ORIG_VERSION}-${SHA}"

          npm version "$TMP_VERSION" --no-git-tag-version

          cp package.json package.json.bak

          jq --arg v "$TMP_VERSION" '.version = $v' package.json > tmp.json && mv tmp.json package.json

      - name: Publish with SHA tag
        run: |
          npm publish --tag beta
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Restore original package.json
        run: mv package.json.bak package.json
